name: Continuous Integration

env:
  MIX_ENV: test

on: push

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        include:
          - elixir: '1.7'
            otp: '20'
          - elixir: '1.8'
            otp: '20'
          - elixir: '1.9'
            otp: '20'
          - elixir: '1.10'
            otp: '21'
          - elixir: '1.11'
            otp: '21'
          - elixir: '1.11'
            otp: '23'

    name: Elixir ${{ matrix.elixir }} (OTP ${{ matrix.otp }})

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - id: install
        name: Install Elixir
        uses: erlef/setup-elixir@v1
        with:
          otp-version: ${{ matrix.otp }}
          elixir-version: ${{ matrix.elixir }}

      - name: Restore cached dependencies
        uses: actions/cache@v2
        with:
          path: deps
          key: deps-${{ runner.os }}-elixir-${{ steps.install.outputs.elixir-version }}-otp-${{ steps.install.outputs.otp-version }}-mix-${{ hashFiles('mix.lock') }}

      - name: Restore cached build
        uses: actions/cache@v2
        with:
          path: _build
          key: build-${{ runner.os }}-elixir-${{ steps.install.outputs.elixir-version }}-otp-${{ steps.install.outputs.otp-version }}-mix-${{ hashFiles('mix.lock') }}

      - name: Install dependencies
        run: mix do deps.get, deps.compile

      - name: Check formatting
        run: mix format --check-formatted

      - name: Compile
        run: mix compile --warnings-as-errors

      - name: Run tests
        run: mix test
