on: push

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-elixir@v1
        with:
          otp-version: "23.2.5"
          elixir-version: "1.11.3"
      - run: mix deps.get
      - run: mix test
