name: Continuous Integration

on: push

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        include:
          - elixir: '1.7'
            otp: '20'
          - elixir: '1.8'
            otp: '20'
          - elixir: '1.9'
            otp: '20'
          - elixir: '1.10'
            otp: '21'
          - elixir: '1.11'
            otp: '21'
          - elixir: '1.11'
            otp: '23'

    name: Elixir ${{ matrix.elixir }} (OTP ${{ matrix.otp }})

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Elixir
        uses: erlef/setup-elixir@v1
        with:
          otp-version: ${{ matrix.otp }}
          elixir-version: ${{ matrix.elixir }}

      - name: Install dependencies
        run: mix do deps.get, deps.compile

      - name: Check formatting
        run: mix format --check-formatted

      - name: Compile
        run: mix compile --warnings-as-errors

      - name: Run tests
        run: mix test
